Add retry mechanism before using conda for the first time (#4337)
Trying to fix conda related errors:
https://github.com/pytorch/test-infra/issues/4155
Error happens during at the beginning of workflow
```
Prepare all required actions
Getting action download info
Download action repository 'conda-incubator/setup-miniconda@v[2](https://github.com/pytorch/test-infra/actions/runs/5448274683/jobs/9911282747?pr=4337#step:7:2).1.1' (SHA:[3](https://github.com/pytorch/test-infra/actions/runs/5448274683/jobs/9911282747?pr=4337#step:7:3)5d1[4](https://github.com/pytorch/test-infra/actions/runs/5448274683/jobs/9911282747?pr=4337#step:7:4)05e78aa3f784fe3ce9a2eb378d5eeb62169)
Run ./test-infra/.github/actions/setup-binary-builds
Run set -euxo pipefail
/github/home/.profile: line 22: conda: command not found
Error: Process completed with exit code 127.
```
And like this as well:

```
Prepare all required actions
Getting action download info
Download action repository 'conda-incubator/setup-miniconda@v[2](https://github.com/pytorch/vision/actions/runs/5443958536/jobs/9901166137#step:6:2).1.1' (SHA:[3](https://github.com/pytorch/vision/actions/runs/5443958536/jobs/9901166137#step:6:3)5d1[4](https://github.com/pytorch/vision/actions/runs/5443958536/jobs/9901166137#step:6:4)05e78aa3f784fe3ce9a2eb378d5eeb62169)
Run ./test-infra/.github/actions/setup-binary-builds
Run set -euxo pipefail

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```