[BE] Fix autoscale (#4299)
Fist of all, fix embarrassing `AttributeError: type object 'datetime.time' has no attribute 'sleep'`. (Hattip to @kit1980 for reporting)

Also, `def main()` is declared as returning `None` so not point returning zeroes there.

Fix all flake8 reported issues except E501