Add release matrix. Make sure domain releases versions are included (#4736)
0. Fix test assets broken by
https://github.com/pytorch/test-infra/pull/4731
1. Add release matrix. Test:
```
[atalman@devvm18003.prn0 /data/users/atalman/test-infra (release_versions_matrix)]$ python3 tools/scripts/generate_release_matrix.py --version 2.1.0
{"torch": "2.1.0", "torchvision": "0.16.0", "torchaudio": "2.1.0", "torchtext": "0.16.0", "tochdata": "0.7.0"}
[atalman@devvm18003.prn0 /data/users/atalman/test-infra (release_versions_matrix)]$ python3 tools/scripts/generate_release_matrix.py --version 2.1.2
Traceback (most recent call last):
  File "tools/scripts/generate_release_matrix.py", line 47, in <module>
    main(sys.argv[1:])
  File "tools/scripts/generate_release_matrix.py", line 41, in main
    raise ValueError(f"{options.version} is not a valid release")
ValueError: 2.1.2 is not a valid release
```


Intent to add domain version validations here:
https://github.com/pytorch/builder/blob/main/test/smoke_test/smoke_test.py#L61