[Nova] Fix Anaconda Upload Issue (#1242)
Uploading our built conda binaries from within the pre-existing conda
environment caused failures of the following form:

```
+ ${CONDA_RUN} /opt/conda/bin/anaconda -t *** upload dist/linux-64/torchvision-0.15.0.dev20221207-py37_cpu.tar.bz2 -u pytorch-nightly --label main --no-progress --force
Using Anaconda API: https://api.anaconda.org/
Using "pytorch-nightly" as upload username
Processing 'dist/linux-64/torchvision-0.15.0.dev20221207-py37_cpu.tar.bz2'
Detecting file type...
File type is "Conda"
Extracting conda attributes for upload
Creating package "torchvision"
Creating release "0.15.0.dev20221207"
Error:  ('"torchvision" could not be found', 404)
```

When we create a fresh conda environment just to install the anaconda
client and do the upload, they all seem to go through. While I haven't
root caused the exact issue causing the failure in the previous
environment, the signal from the test workflows in this PR suggest these
changes fix the issue, and they uploaded all binaries correctly.

As far as the root cause goes, I've tried uploading the binary from
within an existing environment with the same package installed and from
within a fresh environment on both MacOS x86 and Linux machines and I
wasn't able to reproduce it.