Revert "[BE] Update upload bm results GHA" (#7619)
Reverts pytorch/test-infra#7612
Causing multiple failures on CI :
https://github.com/pytorch/pytorch/actions/runs/20446693320/job/58754263235

Error:
```
Traceback (most recent call last):
  File "/home/ec2-user/actions-runner/_work/_actions/pytorch/test-infra/main/.github/actions/upload-benchmark-results/../../scripts/upload_benchmark_results.py", line 380, in <module>
    main()
  File "/home/ec2-user/actions-runner/_work/_actions/pytorch/test-infra/main/.github/actions/upload-benchmark-results/../../scripts/upload_benchmark_results.py", line 375, in main
    warn(f"Find no benchmark results in {args.benchmark_results}")
AttributeError: 'Namespace' object has no attribute 'benchmark_results'
```