Remove distr prefix from macos builds (#4766)
MacOS smoke test started to fail with following error:
```
/opt/homebrew/Caskroom/miniconda/base/bin/conda run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_7018156083_smoke conda install --quiet --yes -c pytorch-nightly -c file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr distr::torchvision

PackagesNotFoundError: The following packages are not available from current channels:

  - distr::torchvision

Current channels:

  - https://conda.anaconda.org/pytorch-nightly
  - file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr
  - defaults
  - https://conda.anaconda.org/distr <-- Here is the error

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org/

and use the search bar at the top of the page.
```

Hence removing distr channel produces expected result.
Please note: followup may be required to make sure file is actually
installed from expected:
``
file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr
`` 
and not ``pytorch-nightly`` or ``pytorch-test``