Classify sccache errors (#1414)
For example, this build failed because it timed out while waiting for
the sccache server to startup

https://github.com/pytorch/pytorch/actions/runs/3946315315/jobs/6754126326

Relevant logs:

```
sccache: Starting the server...
sccache: error: Timed out waiting for server startup
Error: Process completed with exit code 2.
```