runners: make ssm policy an array
Fixes an issue where the SSM parameter policies were not being set correctly.

Resulted in errors like:

ValidationException: Invalid policies input: {"Type":"Expiration","Version":"1.0","Attributes":{"Timestamp":"2025-06-27T19:11:55.437Z"}}.

Signed-off-by: Eli Uriegas <eliuriegas@meta.com>