Fix packer setup steps for Windows AMI builds (#5333)
Fixes packer setup process by adding the mising amazon plugin. Without
this, people would have to manually install the amazon plugin for the
build to work. Now, running `packer init .` auto-installs the packages

Also updates the README to share the full setup instructions

## Without these changes...
Without this, `packer init .` would claim there was nothing to do:
```
(base) ➜  ~/test-infra/aws/ami/windows git:(main) 
packer init .

No plugins requirement found, make sure you reference a Packer config
containing a packer.required_plugins block. See
https://www.packer.io/docs/templates/hcl_templates/blocks/packer
for more info.
```

And `packer build .` would fail with:

```
(base) ➜  ~/test-infra/aws/ami/windows git:(main) 
packer build .
Error: Unknown data type amazon-ami

  on windows.pkr.hcl line 1:
  (source code not available)

known data sources: [hcp-packer-version http null hcp-packer-artifact
hcp-packer-image hcp-packer-iteration]

Error: Unknown source type amazon-ebs

  on windows.pkr.hcl line 40:
  (source code not available)

The source amazon-ebs is unknown by Packer, and is likely part of a plugin that
is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.

https://developer.hashicorp.com/packer/integrations?filter=amazon
``` 

## With these changes
Now `packer init .` installs the missing package and `packer build .`
starts building the AMI:

```
(base) ➜  ~/test-infra/aws/ami/windows git:(main) ✗ 
packer build .
amazon-ebs.windows_ebs_builder: output will be in this color.

==> amazon-ebs.windows_ebs_builder: skip_create_ami was set; not prevalidating AMI name
    amazon-ebs.windows_ebs_builder: Found Image ID: ami-0d62d934fa5f9765a
==> amazon-ebs.windows_ebs_builder: Setting public IP address to true on instance without a subnet ID
==> amazon-ebs.windows_ebs_builder: No VPC ID provided, Packer will use the default VPC
==> amazon-ebs.windows_ebs_builder: Inferring subnet from the selected VPC "vpc-01998e8a540d4b75e"
==> amazon-ebs.windows_ebs_builder: Set subnet as "subnet-0a0b30ec986fe662e"
==> amazon-ebs.windows_ebs_builder: Creating temporary keypair: packer_666b6807-e541-1656-1319-7c61de404b2c
==> amazon-ebs.windows_ebs_builder: Creating temporary security group for this instance: packer_666b680a-f0ef-e53c-ae54-2b0af1ed96bf
==> amazon-ebs.windows_ebs_builder: Authorizing access to port 5986 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs.windows_ebs_builder: Launching a source AWS instance...
==> amazon-ebs.windows_ebs_builder: changing public IP address config to true for instance on subnet "subnet-0a0b30ec986fe662e"
    amazon-ebs.windows_ebs_builder: Instance ID: i-0af407886ebcdfd0a
==> amazon-ebs.windows_ebs_builder: Waiting for instance (i-0af407886ebcdfd0a) to become ready...
==> amazon-ebs.windows_ebs_builder: Waiting for auto-generated password for instance...
    amazon-ebs.windows_ebs_builder: It is normal for this process to take up to 15 minutes,
    amazon-ebs.windows_ebs_builder: but it usually takes around 5. Please wait.
    amazon-ebs.windows_ebs_builder:  
    amazon-ebs.windows_ebs_builder: Password retrieved!
==> amazon-ebs.windows_ebs_builder: Using WinRM communicator to connect: 44.202.239.117
==> amazon-ebs.windows_ebs_builder: Waiting for WinRM to become available...
    amazon-ebs.windows_ebs_builder: WinRM connected.
==> amazon-ebs.windows_ebs_builder: Connected to WinRM!
==> amazon-ebs.windows_ebs_builder: Uploading ./configs/sshd_config => C:\ProgramData\ssh\sshd_config
    amazon-ebs.windows_ebs_builder: sshd_config 272 B / 272 B [===================================================================================================================================================================================================================================] 100.00% 4s
==> amazon-ebs.windows_ebs_builder: Provisioning with Powershell...
==> amazon-ebs.windows_ebs_builder: Provisioning with powershell script: ./scripts/Installers/Install-SSH.ps1
    amazon-ebs.windows_ebs_builder:
    amazon-ebs.windows_ebs_builder:
...
```