Upgrade next-auth to be compatible with node 18 (#3791)
Jobs were failing due our version of next-auth being incompatible with
node 18, so I update the version of next-auth
Example of failure:

https://github.com/pytorch/test-infra/actions/runs/4236404479/jobs/7361187878
```
Run yarn install --frozen-lockfile
yarn install v1.22.19
[1/[4](https://github.com/pytorch/test-infra/actions/runs/4236404479/jobs/7361187878#step:3:5)] Resolving packages...
[2/4] Fetching packages...
error next-auth@4.10.3: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.1[5](https://github.com/pytorch/test-infra/actions/runs/4236404479/jobs/7361187878#step:3:6).0 || ^1[6](https://github.com/pytorch/test-infra/actions/runs/4236404479/jobs/7361187878#step:3:7).13.0". Got "1[8](https://github.com/pytorch/test-infra/actions/runs/4236404479/jobs/7361187878#step:3:9).14.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```


This caused accessToken to disappear from the Session type
(https://next-auth.js.org/getting-started/upgrade-v4#schema-changes) (i
think we were already on v4 so i have no idea why this wasnt an issue
before), so extend the default interface with the accessToken property
in types/next-auth-d.ts
https://next-auth.js.org/getting-started/typescript#extend-default-interface-properties