Update job from 3.9 to 3.10 (#8125)
TorchCodec CI is entirely broken
([example](https://github.com/meta-pytorch/torchcodec/actions/runs/26626629558/job/78464894361?pr=1459)),
and I suspect other repos are broken too. The `setup-binary-builds`
steps fail with:

```
  File "/__w/_temp/pytorch_pkg_helpers_26626629558/lib/python3.9/site-packages/pip/_internal/models/scheme.py", line 13, in <module>
    @dataclass(frozen=True, slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
ERROR conda.cli.main_run:execute(47): `conda run python -m pip install /__w/torchcodec/torchcodec/test-infra/tools/pkg-helpers` failed. (See above for error)
```

It's because `pip` was [recently updated on
`conda`](https://anaconda.org/channels/anaconda/packages/pip/overview)
and is `>3.10` only, but some of the jobs in `test-infra` are still
relying on 3.9. This PR updates jobs to rely on 3.10 instead of 3.9.

Please feel free to commandeer the PR or close it with a better fix (I
just want the TorchCodec CI to be back! :) )