Removing text from nightly job (#7149)
cc @ZainRizvi 

Nightly job failed:

https://github.com/pytorch/test-infra/actions/runs/17643236253/job/50134931363

```
 * [new branch]      nightly    -> origin/nightly
remote: This repository was archived so it is read-only.
fatal: unable to access 'https://github.com/pytorch/text/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```