Expose results from Dr.CI for API caller if requested (#4589)
This change exposes the classification results from Dr.CI for API caller
if the results is requested by setting the `wait4Results` flag.

* By default, `wait4Results` is not set. When it's set, the caller will
wait till the results are ready. I plan to use this in OSS trymerge.
With this, we could use Dr.CI as source of truth instead of having
split-brain logic both in Dr.CI and trymerge.
* Only the list of classified failures are returned atm and I'm not
using pending or successful jobs for anything.
* The list of failures are returned in JSON format

### Testing

* By default, the flag is not set, the query returns right away:
```
curl --request POST \
  --url 'http://localhost:3000/api/drci/drci?prNumber=109919' \
  --data 'repo=pytorch'
```

* When the flag is set, the list of failures is returned:

```
curl --request POST \
  --url 'http://localhost:3000/api/drci/drci?prNumber=109919&wait4Results=true' \
  --data 'repo=pytorch'

{
  "109919": {
    "FAILED": [],
    "FLAKY": [
      {
        "workflow_id": 6280706666,
        "id": 17058522048,
        "name": "linux-focal-rocm5.6-py3.8 / test (distributed, 1, 2, linux.rocm.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:51:30Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058522048",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "distributed/fsdp/test_fsdp_freezing_weights.py::TestFreezingWeights::test_freezing_weights_with_nested_trunk_False_freezing_method_FreezingMethod_GradToNone_freeze_after_wrap_fsdp_True"
        ],
        "failure_line": "FAILED [300.0706s] distributed/fsdp/test_fsdp_freezing_weights.py::TestFreezingWeights::test_freezing_weights_with_nested_trunk_False_freezing_method_FreezingMethod_GradToNone_freeze_after_wrap_fsdp_True - RuntimeError: Process 0 terminated or timed out after 300.05188751220703 seconds",
        "time": "2023-09-23T01:39:15.074773Z"
      }
    ],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 6280706666,
        "id": 17058792764,
        "name": "win-vs2019-cuda11.8-py3 / test (default, 3, 4, windows.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:51:58Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058792764",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol"
        ],
        "failure_line": "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol",
        "time": "2023-09-23T02:03:02.990182Z"
      },
      {
        "workflow_id": 6280706666,
        "id": 17058792840,
        "name": "win-vs2019-cuda11.8-py3 / test (default, 4, 4, windows.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:37:10Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058792840",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol"
        ],
        "failure_line": "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol",
        "time": "2023-09-23T02:03:05.059828Z"
      }
    ],
    "UNSTABLE": [
      {
        "workflow_id": 6280706666,
        "id": 17058776714,
        "name": "linux-focal-cuda11.8-py3.9-gcc9 / test (multigpu, 1, 1, linux.g5.12xlarge.nvidia.gpu, unstable)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:55:23Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058776714",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "distributed/fsdp/test_hsdp_dtensor_state_dict.py::TestHSDPWithDeviceMeshAndDTensor::test_hsdp_init_with_device_mesh"
        ],
        "failure_line": "FAILED [4.6621s] distributed/fsdp/test_hsdp_dtensor_state_dict.py::TestHSDPWithDeviceMeshAndDTensor::test_hsdp_init_with_device_mesh - RuntimeError: Process 3 exited with error code 10 and exception:",
        "time": "2023-09-23T02:01:24.389508Z"
      }
    ]
  }
}
```