setup-linux: Reference setup-nvidia by absolute path
Otherwise, if `setup-linux` action is used without checking out the repo previously, it can fail, for example see [this](https://github.com/pytorch/xla/actions/runs/5054171030/jobs/9078201991):
> ##[group]Run pytorch/test-infra/.github/actions/setup-linux@main
> 
> Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/ec2-user/actions-runner/_work/xla/xla/test-infra/.github/actions/setup-nvidia'. Did you forget to run actions/checkout before running your local action?


copilot:poem